abstract: OpenID Authentication for Catalyst applications
author: Six Apart <cpan@sixapart.com>
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Catalyst-Plugin-Authentication-OpenID
no_index: 
  directory: 
    - t
    - inc
    - t
requires: 
  Catalyst: 0
  LWPx::ParanoidAgent: 0
  Net::OpenID::Consumer: 0
version: 0.02
