name: Catalyst-Plugin-Authentication-OpenID
version: 0.01
abstract: OpenID Authentication for Catalyst applications
author: Six Apart <cpan@sixapart.com>
license: perl
distribution_type: module
requires:
  Catalyst: 0
  Net::OpenID::Consumer: 0
  LWPx::ParanoidAgent: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.36
